Throw stub (#12)
* Ahora todos los tests fallan, tirando una excepcion

* abstrayendo patrón común de checkeo

* arreglando SEGFAULT con RAII

* agregando ejecución en runner

* fix el workflow

diff --git a/.github/workflows/cmake-multi-platform.yml b/.github/workflows/cmake-multi-platform.yml
--- a/.github/workflows/cmake-multi-platform.yml
+++ b/.github/workflows/cmake-multi-platform.yml
@@ -32,18 +32,23 @@ jobs:
           - os: windows-latest
             c_compiler: cl
             cpp_compiler: cl
+            executable: Debug/obligatorio1.exe
           - os: ubuntu-latest
             c_compiler: gcc
             cpp_compiler: g++
+            executable: obligatorio1
           - os: ubuntu-latest
             c_compiler: clang
             cpp_compiler: clang++
+            executable: obligatorio1
           - os: macos-latest
             c_compiler: gcc
             cpp_compiler: g++
+            executable: obligatorio1
           - os: macos-latest
             c_compiler: clang
             cpp_compiler: clang++
+            executable: obligatorio1
         exclude:
           - os: windows-latest
             c_compiler: gcc
@@ -77,3 +82,11 @@ jobs:
     - name: Build
       # Build your program with the given configuration. Note that --config is needed because the default Windows generator is a multi-config generator (Visual Studio generator).
       run: cmake --build ${{ steps.strings.outputs.build-output-dir }} --config ${{ matrix.build_type }}
+
+    - name: Run
+      shell: bash
+      run: |
+        if "${{ steps.strings.outputs.build-output-dir }}/${{ matrix.executable }}" --reporter compact; then
+          echo "Expected the tests to fail, but they passed."
+          exit 1
+        fi
